import { StyleSheet } from 'react-native';
import { ColorPalatte } from '../../Themes';

export const styles = StyleSheet.create({
  large_primary: {
    backgroundColor: ColorPalatte.primaryClr,
    color: ColorPalatte.whiteClr,
    borderRadius: 12,
    height: 44,
    width: '100%',
    gap: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: ColorPalatte.fontSize14,
    fontFamily: 'Outfit-Bold',
  },
  medium_primary: {
    backgroundColor: ColorPalatte.primaryClr,
    color: ColorPalatte.whiteClr,
    borderRadius: 12,
    height: 40,
    width: 154,
    gap: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'Outfit-Bold',
  },
  small_primary: {
    backgroundColor: ColorPalatte.primaryClr,
    color: ColorPalatte.whiteClr,
    borderRadius: 12,
    height: 30,
    minWidth: 100,
    marginRight: 5,
    paddingHorizontal: 5,
    gap: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: ColorPalatte.fontSize12,
    fontFamily: 'Outfit-Bold',
  },
  large_secondary: {
    backgroundColor: ColorPalatte.whiteClr,
    color: ColorPalatte.primaryClr,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: ColorPalatte.primaryClr,
    height: 44,
    width: '100%',
    gap: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: ColorPalatte.fontSize14,
    fontFamily: 'Outfit-Bold',
  },
  medium_secondary: {
    backgroundColor: ColorPalatte.whiteClr,
    color: ColorPalatte.primaryClr,
    borderRadius: 12,
    height: 40,
    width: 154,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: ColorPalatte.primaryClr,
    gap: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: ColorPalatte.fontSize14,
    fontFamily: 'Outfit-Bold',
  },
  small_secondary: {
    backgroundColor: ColorPalatte.whiteClr,
    color: ColorPalatte.primaryClr,
    borderRadius: 12,
    height: 30,
    minWidth: 69,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: ColorPalatte.primaryClr,
    gap: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: ColorPalatte.fontSize12,
    fontFamily: 'Outfit-Bold',
  },
  buttonTextnormal: {
    fontSize: ColorPalatte.fontSize14,
    fontWeight: ColorPalatte.fontFamilyMedium500,
    lineHeight: 21,
  },
  buttonTextsmall: {
    fontSize: ColorPalatte.fontSize12,
    fontWeight: ColorPalatte.fontFamilyRegular400,
    padding: 5,
    fontFamily: 'Outfit-Bold',
  },
  buttonTextPrimary: {
    color: ColorPalatte.whiteClr,
  },
  buttonTextSecondary: {
    color: ColorPalatte.primaryClr,
  },
});
